import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../../helper/svg/svg.dart';
import '../../../../helper/transform/transform.dart';

/* Vector Subtraction 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSubtraction2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: -1.00,
        b: 0.00,
        c: -0.00,
        d: -1.00,
        child: Container(
          width: 152.0.w,
          height: 47.9999885559082.h,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M152 48L0 48C6.45007 48 12.636 45.4714 17.1968 40.9706C21.7577 36.4697 24.32 30.3652 24.32 24C24.32 17.6348 21.7577 11.5303 17.1968 7.02944C12.636 2.52856 6.45007 5.10702e-15 0 1.33227e-15L152 0L152 48Z')
              ..color = Color.fromARGB(255, 255, 255, 255),
            SvgPathPainter.stroke(
              0.25,
              strokeJoin: StrokeJoin.miter,
            )
              ..addPath(
                  'M152 48L152 48.25L152.25 48.25L152.25 48L152 48ZM152 0L152.25 0L152.25 -0.25L152 -0.25L152 0ZM152 47.75L0 47.75L0 48.25L152 48.25L152 47.75ZM0 48.25C6.51531 48.25 12.7644 45.6959 17.3724 41.1485L17.0212 40.7926C12.5075 45.247 6.38482 47.75 0 47.75L0 48.25ZM17.3724 41.1485C21.9806 36.601 24.57 30.4326 24.57 24L24.07 24C24.07 30.2978 21.5349 36.3384 17.0212 40.7926L17.3724 41.1485ZM24.57 24C24.57 17.5674 21.9806 11.399 17.3724 6.85149L17.0212 7.20738C21.5349 11.6616 24.07 17.7022 24.07 24L24.57 24ZM17.3724 6.85149C12.7644 2.30411 6.51531 -0.25 1.46307e-16 -0.25L-1.46307e-16 0.25C6.38482 0.25 12.5075 2.75302 17.0212 7.20738L17.3724 6.85149ZM2.19123e-18 0.25L152 0.25L152 -0.25L-2.19123e-18 -0.25L2.19123e-18 0.25ZM151.75 0L151.75 48L152.25 48L152.25 0L151.75 0Z')
              ..color = Color.fromARGB(255, 14, 76, 143)
              ..addClipPath(
                  'M152 48L0 48C6.45007 48 12.636 45.4714 17.1968 40.9706C21.7577 36.4697 24.32 30.3652 24.32 24C24.32 17.6348 21.7577 11.5303 17.1968 7.02944C12.636 2.52856 6.45007 5.10702e-15 0 1.33227e-15L152 0L152 48Z'),
          ]),
        ));
  }
}
