import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

/* Text تسجيل دخول
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget394 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      AppLocalizations.of(context)!.login,
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.5.h,
        fontSize: 12.0.sp,
        fontFamily: 'Tajawal',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 44, 44, 44),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}