/* Group Group 40943
    Autogenerated by FlutLab FTF Generator
  */
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../../helper/transform/transform.dart';
import '../register_button/GeneratedSubtraction2Widget.dart';
import 'log_name.dart';
import 'out_shape.dart';

class GeneratedGroup40943Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.translate(
      y:10.h,
      x: -10.w,
      child: Container(
        width: 152.0.w,
        height: 48.0.h,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // //overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 152.0.w,
                height: 48.0.h,
                child: GeneratedSubtraction1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 152.0.w,
                height: 48.0.h,
                child: GeneratedSubtraction2Widget(),
              ),
              Positioned(
                left: 37.0.w,
                top: 12.0.h,
                right: null,
                bottom: null,
                width: 94.0.w,
                height: 27.0.h,
                child: GeneratedWidget394(),
              )
            ]),
      ),
    );
  }
}